### ISSUE TITLE
cli v2.1 cmf pack on HTML throws error

### ISSUE THREAD

**Issue by mpamarques** [criticalmanufacturing/cli#129]
Hi,

On both 2.0 and 2.1 I have the following error with cmf pack command on my HTML package:

  Generating Cmf.Custom.Html.1.33.0
  Generating Presentation config.json
  Value cannot be null. (Parameter 'stream') | InnerException: Value cannot be null. (Parameter 'stream')
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Cmf.Common.Cli.Utilities.CliException: Value cannot be null. (Parameter 'stream')
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'stream')
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at Cmf.Common.Cli.Utilities.GenericUtilities.GetEmbeddedResourceContent(String resourceName) in /home/runner/work/cli/cli/cmf-cli/Utilities/GenericUtilities.cs:line 35
   at Cmf.Common.Cli.Handlers.PresentationPackageTypeHandler.GeneratePresentationConfigFile(IDirectoryInfo packageOutputDir) in /home/runner/work/cli/cli/cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs:line 69
   at Cmf.Common.Cli.Handlers.PresentationPackageTypeHandler.Pack(IDirectoryInfo packageOutputDir, IDirectoryInfo outputDir) in /home/runner/work/cli/cli/cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs:line 212
   at Cmf.Common.Cli.Commands.PackCommand.Execute(CmfPackage cmfPackage, IDirectoryInfo outputDir, Boolean force) in /home/runner/work/cli/cli/cmf-cli/Commands/pack/PackCommand.cs:line 97
   --- End of inner exception stack trace ---
   at Cmf.Common.Cli.Commands.PackCommand.Execute(CmfPackage cmfPackage, IDirectoryInfo outputDir, Boolean force) in /home/runner/work/cli/cli/cmf-cli/Commands/pack/PackCommand.cs:line 101
   at Cmf.Common.Cli.Commands.PackCommand.Execute(IDirectoryInfo workingDir, IDirectoryInfo outputDir, Boolean force) in /home/runner/work/cli/cli/cmf-cli/Commands/pack/PackCommand.cs:line 64
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
   
   If you need more information please let me know.

**Comment by m-s-** [comment]
Fixed by #130
